package com.nice.qa.model.api.dto;

import com.nice.qa.entity.DevRequestStatus;
import jakarta.validation.constraints.NotBlank;

/**
 * 개발요청서 신규 저장 및 수정 공용 요청 DTO
 * (Shared request DTO for both creating and updating a DevRequest).
 *
 * <p>이 레코드는 두 가지 시나리오에서 공통으로 사용된다.</p>
 * <ol>
 *   <li><b>LLM 결과 저장</b>: {@code generate} API(무저장 초안 생성)가 반환한 결과를
 *       그대로 이 DTO 에 담아 저장 API 로 전달한다.</li>
 *   <li><b>위저드 입력 임시 저장</b>: 사용자가 폼 작성 중인 상태를 중간 저장할 때는
 *       LLM 결과 필드({@code combinedMarkdown}, {@code flowDiagram} 등)를 {@code null} 로 두어도 된다.</li>
 * </ol>
 *
 * <p>This record is used for both save (create) and update operations.
 * All LLM-generated fields are optional so that draft saves (without LLM output)
 * are also supported.</p>
 *
 * @param title               요청서 제목 — 필수 값 (Required request title)
 * @param categoryPath        카테고리 경로 (예: "결제창 / 카드"), 선택 사항
 *                            (Optional category hierarchy path, e.g. "결제창 / 카드")
 * @param status              요청서 상태 열거값. {@code null} 이면 서비스 레이어가 {@code DRAFT} 로 처리한다.
 *                            (Status enum. If {@code null}, the service layer defaults to {@code DRAFT}.)
 * @param author              작성자 이름, 선택 사항 (Optional author name)
 * @param dept                작성자 소속 부서, 선택 사항 (Optional department name)
 * @param details             위저드 단계별 입력 원본 JSON (자유 형식), 선택 사항
 *                            (Optional raw wizard input stored as free-form JSON)
 * @param combinedMarkdown    Gemini LLM 이 생성한 종합 마크다운 요건 정의서, 선택 사항
 *                            (Optional combined Markdown requirements document generated by Gemini LLM)
 * @param flowDiagram         mxGraph XML 또는 PlantUML 형식의 플로우 다이어그램 소스, 선택 사항
 *                            (Optional flow diagram source in mxGraph XML or PlantUML format)
 * @param unconfirmedSection  추가 확인이 필요한 항목 (JSON 또는 마크다운 형식), 선택 사항
 *                            (Optional items requiring further clarification, stored as JSON or Markdown)
 */
public record DevRequestSaveRequest(

        /**
         * 요청서 제목 — 저장 시 반드시 제공해야 하는 필수 필드.
         * (Required title of the development request.)
         */
        @NotBlank String title,

        /**
         * 카테고리 계층 경로 — 슬래시(/) 구분 문자열 (예: "결제창 / 카드").
         * 미입력 시 {@code null} 허용.
         * (Category hierarchy path separated by slashes, e.g. "결제창 / 카드". Nullable.)
         */
        String categoryPath,

        /**
         * 요청서 현재 상태.
         * {@code null} 전달 시 서비스 레이어에서 {@link DevRequestStatus#DRAFT} 로 기본 처리한다.
         * (Current status of the request.
         * When {@code null}, the service layer defaults to {@link DevRequestStatus#DRAFT}.)
         */
        DevRequestStatus status,

        /**
         * 작성자 이름. 선택 사항이며 미입력 시 {@code null} 허용.
         * (Author name. Optional; nullable.)
         */
        String author,

        /**
         * 작성자 소속 부서명. 선택 사항이며 미입력 시 {@code null} 허용.
         * (Author's department name. Optional; nullable.)
         */
        String dept,

        /**
         * 위저드 각 단계에서 수집한 입력값 전체를 담은 원본 JSON 문자열 (자유 형식).
         * LLM 호출 없이 임시 저장 시에도 사용된다.
         * (Raw JSON string containing all wizard step inputs in free-form format.
         * Also used for intermediate saves without LLM invocation.)
         */
        String details,

        /**
         * Gemini LLM 이 생성한 종합 마크다운 요건 정의서.
         * {@code generate} API 결과를 저장할 때 채워지며, 임시 저장 시에는 {@code null} 가능.
         * (Combined Markdown requirements document produced by the Gemini LLM.
         * Populated when saving the result of the {@code generate} API; {@code null} for draft saves.)
         */
        String combinedMarkdown,

        /**
         * mxGraph XML 또는 PlantUML 형식의 플로우 다이어그램 소스 문자열.
         * LLM 생성 결과를 저장할 때 채워지며, 임시 저장 시에는 {@code null} 가능.
         * (Flow diagram source in mxGraph XML or PlantUML format.
         * Populated when saving LLM output; {@code null} for draft saves.)
         */
        String flowDiagram,

        /**
         * 검토 과정에서 추가 확인이 필요하다고 판단된 항목들 (JSON 또는 마크다운).
         * LLM 결과에 포함되어 전달되며, 임시 저장 시에는 {@code null} 가능.
         * (Items flagged as requiring further clarification, stored as JSON or Markdown.
         * Populated from LLM output; {@code null} for draft saves.)
         */
        String unconfirmedSection
) {
}
