package com.nice.qa.model.api.dto;

import com.nice.qa.entity.DevRequest;
import com.nice.qa.entity.DevRequestStatus;

import java.time.LocalDateTime;

/**
 * 개발요청서 상세 조회 응답 DTO (Detail Response DTO for DevRequest).
 *
 * <p>목록 조회({@link DevRequestSummary})와 달리 본문 텍스트 전체를 포함한다.
 * 구체적으로 위저드 입력 원본({@code details}), Gemini 종합 마크다운({@code combinedMarkdown}),
 * 플로우 다이어그램({@code flowDiagram}), 미확인 항목({@code unconfirmedSection})을 모두 반환한다.</p>
 *
 * <p>Unlike the list summary, this record carries all body fields including
 * the combined Markdown document, flow diagram source, and unconfirmed sections.</p>
 *
 * @param id                  개발요청서 고유 식별자 (Unique primary key of the DevRequest entity)
 * @param title               요청서 제목 (Title of the development request)
 * @param categoryPath        카테고리 경로 (예: "결제창 / 카드")
 *                            (Category path, e.g. "결제창 / 카드")
 * @param status              요청서 현재 상태 열거값 (Current status enum value of the request)
 * @param statusLabel         상태 열거값의 한국어 표시 레이블 (Korean display label for the status enum)
 * @param author              작성자 이름 (Name of the person who authored the request)
 * @param dept                작성자 소속 부서 (Department of the author)
 * @param createdAt           최초 생성 일시 (Timestamp when the record was first created)
 * @param updatedAt           마지막 수정 일시 (Timestamp of the most recent update)
 * @param details             위저드 입력 원본 데이터 (JSON 자유 형식)
 *                            (Raw wizard input data stored as free-form JSON)
 * @param combinedMarkdown    Gemini LLM 이 생성한 종합 마크다운 문서
 *                            (Combined Markdown document generated by the Gemini LLM)
 * @param flowDiagram         mxGraph XML 또는 PlantUML 형식의 플로우 다이어그램 소스
 *                            (Flow diagram source in mxGraph XML or PlantUML format)
 * @param unconfirmedSection  추가 확인이 필요한 항목 (JSON 또는 마크다운 형식)
 *                            (Items that require further confirmation, stored as JSON or Markdown)
 */
public record DevRequestDetail(
        /** 개발요청서 고유 식별자 (Primary key) */
        Long id,

        /** 요청서 제목 (Request title) */
        String title,

        /** 카테고리 경로 — 슬래시(/) 구분 계층 문자열, 예: "결제창 / 카드"
         *  (Category hierarchy path separated by slashes) */
        String categoryPath,

        /** 요청서 현재 상태 열거값 (Current status enum) */
        DevRequestStatus status,

        /** {@link DevRequestStatus} 열거값에 대응하는 한국어 표시 레이블
         *  (Korean display label derived from the status enum) */
        String statusLabel,

        /** 작성자 이름 (Author's name) */
        String author,

        /** 작성자 소속 부서 (Author's department) */
        String dept,

        /** 레코드 최초 생성 일시 (Record creation timestamp) */
        LocalDateTime createdAt,

        /** 레코드 마지막 수정 일시 (Record last-updated timestamp) */
        LocalDateTime updatedAt,

        /** 위저드 단계별 입력값을 담은 원본 JSON 문자열
         *  (Raw JSON string containing all wizard step inputs) */
        String details,

        /** Gemini LLM 이 생성한 종합 마크다운 요건 정의서
         *  (Full requirements document in Markdown, generated by the Gemini LLM) */
        String combinedMarkdown,

        /** mxGraph XML 또는 PlantUML 형식의 플로우 다이어그램 소스 문자열
         *  (Flow diagram source string in mxGraph XML or PlantUML format) */
        String flowDiagram,

        /** 검토 과정에서 추가 확인이 필요하다고 판단된 항목들 (JSON 또는 마크다운)
         *  (Items flagged as needing further clarification, stored as JSON or Markdown) */
        String unconfirmedSection
) {
    /**
     * {@link DevRequest} 엔티티를 상세 조회 응답 DTO 로 변환한다 (Factory method).
     *
     * <p>상태({@code status})가 {@code null} 인 경우 {@code statusLabel} 도 {@code null} 로 설정된다.</p>
     *
     * <p>Converts a {@link DevRequest} JPA entity into this detail DTO.
     * If {@code status} is {@code null}, {@code statusLabel} is also set to {@code null}.</p>
     *
     * @param e 변환 대상 {@link DevRequest} 엔티티 (Source DevRequest entity to convert)
     * @return 엔티티의 모든 필드가 복사된 {@link DevRequestDetail} 인스턴스
     *         (A new {@link DevRequestDetail} instance populated from the entity)
     */
    public static DevRequestDetail from(DevRequest e) {
        return new DevRequestDetail(
                e.getId(),
                e.getTitle(),
                e.getCategoryPath(),
                e.getStatus(),
                e.getStatus() != null ? e.getStatus().getLabel() : null,
                e.getAuthor(),
                e.getDept(),
                e.getCreatedAt(),
                e.getUpdatedAt(),
                e.getDetails(),
                e.getCombinedMarkdown(),
                e.getFlowDiagram(),
                e.getUnconfirmedSection()
        );
    }
}
